# Generated by Django 4.2.5 on 2023-11-29 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartFarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sfid', models.CharField(max_length=10)),
                ('crop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crops.smartfarmcrop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SmartFarmSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soilwarning', models.TextField(auto_created=True, null=True)),
                ('humwarning', models.TextField(auto_created=True, null=True)),
                ('tempwarning', models.TextField(auto_created=True, null=True)),
                ('watertempwarning', models.TextField(auto_created=True, null=True)),
                ('waterlevelwarning', models.TextField(auto_created=True, null=True)),
                ('remotepower', models.BooleanField(blank=True, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('light', models.IntegerField(blank=True, null=True)),
                ('soil', models.IntegerField(blank=True, null=True)),
                ('ledpower', models.BooleanField(blank=True, default=0, null=True)),
                ('ledstate', models.BooleanField(blank=True, default=0, null=True)),
                ('ledtoggle', models.BooleanField(blank=True, default=0, null=True)),
                ('ledautotoggle', models.BooleanField(blank=True, default=0, null=True)),
                ('ledstarttimevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('ledstartminutevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('ledendtimevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('ledendminutevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('waterpumppower', models.BooleanField(blank=True, default=0, null=True)),
                ('waterpumpstate', models.BooleanField(blank=True, default=0, null=True)),
                ('waterpumptoggle', models.BooleanField(blank=True, default=0, null=True)),
                ('waterpumpautotoggle', models.BooleanField(blank=True, default=0, null=True)),
                ('waterpumpstarttime', models.IntegerField(blank=True, default=0, null=True)),
                ('waterpumprunningtime', models.IntegerField(blank=True, default=0, null=True)),
                ('waterlevelvoltage', models.FloatField(blank=True, default=0, null=True)),
                ('watertemperature', models.FloatField(blank=True, default=0, null=True)),
                ('fanpower', models.BooleanField(blank=True, default=0, null=True)),
                ('fanstate', models.BooleanField(blank=True, default=0, null=True)),
                ('fantoggle', models.BooleanField(blank=True, default=0, null=True)),
                ('fanautotoggle', models.BooleanField(blank=True, default=0, null=True)),
                ('fanstarttimevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('fanstartminutevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('fanendtimevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('fanendminutevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('doorpower', models.BooleanField(blank=True, default=0, null=True)),
                ('doorstate', models.BooleanField(blank=True, default=0, null=True)),
                ('doortoggle', models.BooleanField(blank=True, default=0, null=True)),
                ('doorautotoggle', models.BooleanField(blank=True, default=0, null=True)),
                ('doorstarttimevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('doorstartminutevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('doorendtimevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('doorendminutevalue', models.IntegerField(blank=True, default=0, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('smartfarm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='server.smartfarm')),
            ],
        ),
    ]
